version: '3.4'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana:/var/lib/grafana

  chronograf:
    image: chronograf
    command: --influxdb-url=http://influxdb:8086
    ports:
    - 8888:8888
    volumes:
    - chronograf:/var/lib/chronograf

volumes:
  influxdb: {}
  grafana: {}
  chronograf: {}